[2023-10-01T19:35:30.833+0200] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: MYDBDAG.InsertDataElasticSearch manual__2023-10-01T17:35:23.911213+00:00 [queued]>
[2023-10-01T19:35:30.836+0200] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: MYDBDAG.InsertDataElasticSearch manual__2023-10-01T17:35:23.911213+00:00 [queued]>
[2023-10-01T19:35:30.836+0200] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2023-10-01T19:35:30.843+0200] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): InsertDataElasticSearch> on 2023-10-01 17:35:23.911213+00:00
[2023-10-01T19:35:30.846+0200] {standard_task_runner.py:57} INFO - Started process 77205 to run task
[2023-10-01T19:35:30.848+0200] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'MYDBDAG', 'InsertDataElasticSearch', 'manual__2023-10-01T17:35:23.911213+00:00', '--job-id', '2084', '--raw', '--subdir', 'DAGS_FOLDER/databaseDAG.py', '--cfg-path', '/tmp/tmpmef01ygb']
[2023-10-01T19:35:30.849+0200] {standard_task_runner.py:85} INFO - Job 2084: Subtask InsertDataElasticSearch
[2023-10-01T19:35:30.866+0200] {task_command.py:415} INFO - Running <TaskInstance: MYDBDAG.InsertDataElasticSearch manual__2023-10-01T17:35:23.911213+00:00 [running]> on host radtrz-B450-AORUS-ELITE
[2023-10-01T19:35:30.901+0200] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='radtrz' AIRFLOW_CTX_DAG_ID='MYDBDAG' AIRFLOW_CTX_TASK_ID='InsertDataElasticSearch' AIRFLOW_CTX_EXECUTION_DATE='2023-10-01T17:35:23.911213+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-01T17:35:23.911213+00:00'
[2023-10-01T19:35:30.901+0200] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/radtrz/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/radtrz/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/radtrz/airflow/dags/databaseDAG.py", line 29, in insertElasticsearch
    es = Elasticsearch()
  File "/home/radtrz/.local/lib/python3.10/site-packages/elasticsearch/_sync/client/__init__.py", line 194, in __init__
    raise ValueError("Either 'hosts' or 'cloud_id' must be specified")
ValueError: Either 'hosts' or 'cloud_id' must be specified
[2023-10-01T19:35:30.903+0200] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=MYDBDAG, task_id=InsertDataElasticSearch, execution_date=20231001T173523, start_date=20231001T173530, end_date=20231001T173530
[2023-10-01T19:35:30.909+0200] {standard_task_runner.py:104} ERROR - Failed to execute job 2084 for task InsertDataElasticSearch (Either 'hosts' or 'cloud_id' must be specified; 77205)
[2023-10-01T19:35:30.939+0200] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-01T19:35:30.946+0200] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
