[2023-10-01T19:40:42.540+0200] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: MYDBDAG.InsertDataElasticSearch scheduled__2023-10-01T00:15:00+00:00 [queued]>
[2023-10-01T19:40:42.543+0200] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: MYDBDAG.InsertDataElasticSearch scheduled__2023-10-01T00:15:00+00:00 [queued]>
[2023-10-01T19:40:42.543+0200] {taskinstance.py:1359} INFO - Starting attempt 2 of 2
[2023-10-01T19:40:42.551+0200] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): InsertDataElasticSearch> on 2023-10-01 00:15:00+00:00
[2023-10-01T19:40:42.554+0200] {standard_task_runner.py:57} INFO - Started process 78346 to run task
[2023-10-01T19:40:42.556+0200] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'MYDBDAG', 'InsertDataElasticSearch', 'scheduled__2023-10-01T00:15:00+00:00', '--job-id', '2120', '--raw', '--subdir', 'DAGS_FOLDER/databaseDAG.py', '--cfg-path', '/tmp/tmphz8ouwb_']
[2023-10-01T19:40:42.557+0200] {standard_task_runner.py:85} INFO - Job 2120: Subtask InsertDataElasticSearch
[2023-10-01T19:40:42.575+0200] {task_command.py:415} INFO - Running <TaskInstance: MYDBDAG.InsertDataElasticSearch scheduled__2023-10-01T00:15:00+00:00 [running]> on host radtrz-B450-AORUS-ELITE
[2023-10-01T19:40:42.608+0200] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='radtrz' AIRFLOW_CTX_DAG_ID='MYDBDAG' AIRFLOW_CTX_TASK_ID='InsertDataElasticSearch' AIRFLOW_CTX_EXECUTION_DATE='2023-10-01T00:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-01T00:15:00+00:00'
[2023-10-01T19:40:42.616+0200] {_transport.py:335} INFO - POST http://127.0.0.1:9200/frompostgresql/_doc [status:500 duration:0.003s]
[2023-10-01T19:40:42.616+0200] {_node_pool.py:249} WARNING - Node <Urllib3HttpNode(http://127.0.0.1:9200)> has failed for 1 times in a row, putting on 1 second timeout
[2023-10-01T19:40:42.617+0200] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/radtrz/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/radtrz/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/radtrz/airflow/dags/databaseDAG.py", line 33, in insertElasticsearch
    res = es.index(index='frompostgresql', document='doc')
  File "/home/radtrz/.local/lib/python3.10/site-packages/elasticsearch/_sync/client/utils.py", line 414, in wrapped
    return api(*args, **kwargs)
  File "/home/radtrz/.local/lib/python3.10/site-packages/elasticsearch/_sync/client/__init__.py", line 2322, in index
    return self.perform_request(  # type: ignore[return-value]
  File "/home/radtrz/.local/lib/python3.10/site-packages/elasticsearch/_sync/client/_base.py", line 320, in perform_request
    raise HTTP_EXCEPTIONS.get(meta.status, ApiError)(
elasticsearch.ApiError: ApiError(500, 'not_x_content_exception', 'Compressor detection can only be called on some xcontent bytes or compressed xcontent bytes')
[2023-10-01T19:40:42.619+0200] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=MYDBDAG, task_id=InsertDataElasticSearch, execution_date=20231001T001500, start_date=20231001T174042, end_date=20231001T174042
[2023-10-01T19:40:42.625+0200] {standard_task_runner.py:104} ERROR - Failed to execute job 2120 for task InsertDataElasticSearch (ApiError(500, 'not_x_content_exception', 'Compressor detection can only be called on some xcontent bytes or compressed xcontent bytes'); 78346)
[2023-10-01T19:40:42.647+0200] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-01T19:40:42.655+0200] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
